version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password_change_me
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - redpanda-interop
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password_change_me
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password_change_me
    # KC_HOSTNAME: fragjetzt-staging.mni.thm.de
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_FRONTEND_URL: "http://fragjetzt-staging.mni.thm.de:8180"
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-db
    networks:
      - redpanda-interop
    restart: unless-stopped

networks:
  redpanda-interop:
    external: true

volumes:
  keycloak-db-data:
